-- ============================================================
-- 01. 테이블 오버뷰 — 행 수, 기간, 지역 커버리지
-- 실행 순서: 각 쿼리를 하나씩 실행 (LIMIT 10 테스트 → 전체)
-- 크레딧: ~$0.01 이하 (SELECT COUNT 수준)
-- ============================================================

-- --------------------------------------------------------
-- A. 전체 테이블 행 수 확인
-- --------------------------------------------------------

-- A-1. 리치고 — 아파트 시세
SELECT '리치고_시세' AS src, COUNT(*) AS rows
FROM KOREAN_POPULATION__APARTMENT_MARKET_PRICE_DATA
    .HACKATHON_2025Q2.REGION_APT_RICHGO_MARKET_PRICE_M_H;

-- A-2. 리치고 — 인구
SELECT '리치고_인구' AS src, COUNT(*) AS rows
FROM KOREAN_POPULATION__APARTMENT_MARKET_PRICE_DATA
    .HACKATHON_2025Q2.REGION_MOIS_POPULATION_GENDER_AGE_M_H;

-- A-3. 리치고 — 영유아 비율
SELECT '리치고_영유아' AS src, COUNT(*) AS rows
FROM KOREAN_POPULATION__APARTMENT_MARKET_PRICE_DATA
    .HACKATHON_2025Q2.REGION_MOIS_POPULATION_AGE_UNDER5_PER_FEMALE_20TO40_M_H;

-- A-4. SPH — 유동인구
SELECT 'SPH_유동인구' AS src, COUNT(*) AS rows
FROM SEOUL_DISTRICTLEVEL_DATA_FLOATING_POPULATION_CONSUMPTION_AND_ASSETS
    .GRANDATA.FLOATING_POPULATION_INFO;

-- A-5. SPH — 카드 소비
SELECT 'SPH_카드소비' AS src, COUNT(*) AS rows
FROM SEOUL_DISTRICTLEVEL_DATA_FLOATING_POPULATION_CONSUMPTION_AND_ASSETS
    .GRANDATA.CARD_SALES_INFO;

-- A-6. SPH — 자산/소득
SELECT 'SPH_자산소득' AS src, COUNT(*) AS rows
FROM SEOUL_DISTRICTLEVEL_DATA_FLOATING_POPULATION_CONSUMPTION_AND_ASSETS
    .GRANDATA.ASSET_INCOME_INFO;

-- A-7. SPH — 코드 마스터
SELECT 'SPH_코드마스터' AS src, COUNT(*) AS rows
FROM SEOUL_DISTRICTLEVEL_DATA_FLOATING_POPULATION_CONSUMPTION_AND_ASSETS
    .GRANDATA.CODE_MASTER;

-- A-8. SPH — 지역 마스터
SELECT 'SPH_지역마스터' AS src, COUNT(*) AS rows
FROM SEOUL_DISTRICTLEVEL_DATA_FLOATING_POPULATION_CONSUMPTION_AND_ASSETS
    .GRANDATA.M_SCCO_MST;

-- --------------------------------------------------------
-- B. 지역 단위 커버리지 — 구/동 몇 개인지
-- --------------------------------------------------------

-- B-1. 리치고: 서울 구 단위 목록
SELECT SGG, COUNT(DISTINCT EMD) AS dong_count, COUNT(*) AS rows
FROM KOREAN_POPULATION__APARTMENT_MARKET_PRICE_DATA
    .HACKATHON_2025Q2.REGION_APT_RICHGO_MARKET_PRICE_M_H
WHERE SD = '서울'
GROUP BY SGG
ORDER BY SGG;

-- B-2. SPH: 구 단위 목록 (M_SCCO_MST)
SELECT CITY_KOR_NAME, DISTRICT_KOR_NAME, PROVINCE_CODE, CITY_CODE, DISTRICT_CODE
FROM SEOUL_DISTRICTLEVEL_DATA_FLOATING_POPULATION_CONSUMPTION_AND_ASSETS
    .GRANDATA.M_SCCO_MST
ORDER BY CITY_KOR_NAME, DISTRICT_KOR_NAME
LIMIT 50;

-- B-3. SPH 유동인구: 구 단위 목록
SELECT DISTINCT CITY_CODE, DISTRICT_CODE
FROM SEOUL_DISTRICTLEVEL_DATA_FLOATING_POPULATION_CONSUMPTION_AND_ASSETS
    .GRANDATA.FLOATING_POPULATION_INFO
ORDER BY CITY_CODE, DISTRICT_CODE;

-- --------------------------------------------------------
-- C. 시간 범위 확인
-- --------------------------------------------------------

-- C-1. 리치고 시세 기간
SELECT MIN(YYYYMMDD) AS min_date, MAX(YYYYMMDD) AS max_date,
       COUNT(DISTINCT YYYYMMDD) AS date_count
FROM KOREAN_POPULATION__APARTMENT_MARKET_PRICE_DATA
    .HACKATHON_2025Q2.REGION_APT_RICHGO_MARKET_PRICE_M_H;

-- C-2. SPH 유동인구 기간
SELECT MIN(STANDARD_YEAR_MONTH) AS min_ym, MAX(STANDARD_YEAR_MONTH) AS max_ym,
       COUNT(DISTINCT STANDARD_YEAR_MONTH) AS period_count
FROM SEOUL_DISTRICTLEVEL_DATA_FLOATING_POPULATION_CONSUMPTION_AND_ASSETS
    .GRANDATA.FLOATING_POPULATION_INFO;

-- C-3. SPH 카드소비 기간 (STANDARD_YEAR_MONTH 컬럼 가정)
SELECT MIN(STANDARD_YEAR_MONTH) AS min_ym, MAX(STANDARD_YEAR_MONTH) AS max_ym,
       COUNT(DISTINCT STANDARD_YEAR_MONTH) AS period_count
FROM SEOUL_DISTRICTLEVEL_DATA_FLOATING_POPULATION_CONSUMPTION_AND_ASSETS
    .GRANDATA.CARD_SALES_INFO;

-- --------------------------------------------------------
-- D. 샘플 데이터 확인 (LIMIT 10)
-- --------------------------------------------------------

-- D-1. 유동인구 샘플
SELECT *
FROM SEOUL_DISTRICTLEVEL_DATA_FLOATING_POPULATION_CONSUMPTION_AND_ASSETS
    .GRANDATA.FLOATING_POPULATION_INFO
LIMIT 10;

-- D-2. 카드소비 샘플
SELECT *
FROM SEOUL_DISTRICTLEVEL_DATA_FLOATING_POPULATION_CONSUMPTION_AND_ASSETS
    .GRANDATA.CARD_SALES_INFO
LIMIT 10;

-- D-3. 자산/소득 샘플
SELECT *
FROM SEOUL_DISTRICTLEVEL_DATA_FLOATING_POPULATION_CONSUMPTION_AND_ASSETS
    .GRANDATA.ASSET_INCOME_INFO
LIMIT 10;

-- D-4. 리치고 시세 샘플
SELECT *
FROM KOREAN_POPULATION__APARTMENT_MARKET_PRICE_DATA
    .HACKATHON_2025Q2.REGION_APT_RICHGO_MARKET_PRICE_M_H
WHERE SD = '서울'
LIMIT 10;
