-- ============================================================
-- 03. 데이터 품질 분석 — NULL 비율, 이상치, 커버리지
-- 크레딧: ~$0.05
-- ============================================================

-- --------------------------------------------------------
-- A. MBTI 핵심 컬럼 NULL 비율 확인
-- NULL 30% 이상이면 대안 컬럼 필요
-- --------------------------------------------------------

-- A-1. SPH 유동인구 NULL 체크
SELECT
    COUNT(*) AS total_rows,
    ROUND(SUM(CASE WHEN RESIDENTIAL_POPULATION IS NULL THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) AS null_pct_residential,
    ROUND(SUM(CASE WHEN VISITING_POPULATION IS NULL THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) AS null_pct_visiting,
    ROUND(SUM(CASE WHEN WORKING_POPULATION IS NULL THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) AS null_pct_working,
    ROUND(SUM(CASE WHEN TIME_SLOT IS NULL THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) AS null_pct_timeslot,
    ROUND(SUM(CASE WHEN WEEKDAY_WEEKEND IS NULL THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) AS null_pct_weekday
FROM SEOUL_DISTRICTLEVEL_DATA_FLOATING_POPULATION_CONSUMPTION_AND_ASSETS
    .GRANDATA.FLOATING_POPULATION_INFO;

-- A-2. SPH 카드소비 NULL 체크
SELECT
    COUNT(*) AS total_rows,
    ROUND(SUM(CASE WHEN FOOD_SALES IS NULL THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) AS null_pct_food,
    ROUND(SUM(CASE WHEN COFFEE_SALES IS NULL THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) AS null_pct_coffee,
    ROUND(SUM(CASE WHEN ENTERTAINMENT_SALES IS NULL THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) AS null_pct_entertainment,
    ROUND(SUM(CASE WHEN SPORTS_CULTURE_LEISURE_SALES IS NULL THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) AS null_pct_sports,
    ROUND(SUM(CASE WHEN MEDICAL_SALES IS NULL THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) AS null_pct_medical,
    ROUND(SUM(CASE WHEN EDUCATION_ACADEMY_SALES IS NULL THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) AS null_pct_edu,
    ROUND(SUM(CASE WHEN E_COMMERCE_SALES IS NULL THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) AS null_pct_ecom,
    ROUND(SUM(CASE WHEN TOTAL_SALES IS NULL THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) AS null_pct_total
FROM SEOUL_DISTRICTLEVEL_DATA_FLOATING_POPULATION_CONSUMPTION_AND_ASSETS
    .GRANDATA.CARD_SALES_INFO;

-- A-3. SPH 자산/소득 NULL 체크
SELECT
    COUNT(*) AS total_rows,
    ROUND(SUM(CASE WHEN AVERAGE_INCOME IS NULL THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) AS null_pct_income,
    ROUND(SUM(CASE WHEN MEDIAN_INCOME IS NULL THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) AS null_pct_median_income,
    ROUND(SUM(CASE WHEN AVERAGE_ASSET_AMOUNT IS NULL THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) AS null_pct_asset,
    ROUND(SUM(CASE WHEN AVERAGE_SCORE IS NULL THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) AS null_pct_credit,
    ROUND(SUM(CASE WHEN OWN_HOUSING_COUNT IS NULL THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) AS null_pct_housing,
    ROUND(SUM(CASE WHEN RATE_INCOME_OVER_70M IS NULL THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) AS null_pct_high_income
FROM SEOUL_DISTRICTLEVEL_DATA_FLOATING_POPULATION_CONSUMPTION_AND_ASSETS
    .GRANDATA.ASSET_INCOME_INFO;

-- A-4. 리치고 시세 NULL 체크
SELECT
    COUNT(*) AS total_rows,
    ROUND(SUM(CASE WHEN MEME_PRICE_PER_SUPPLY_PYEONG IS NULL THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) AS null_pct_meme,
    ROUND(SUM(CASE WHEN JEONSE_PRICE_PER_SUPPLY_PYEONG IS NULL THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) AS null_pct_jeonse,
    ROUND(SUM(CASE WHEN TOTAL_HOUSEHOLDS IS NULL THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) AS null_pct_households
FROM KOREAN_POPULATION__APARTMENT_MARKET_PRICE_DATA
    .HACKATHON_2025Q2.REGION_APT_RICHGO_MARKET_PRICE_M_H
WHERE SD = '서울';


-- --------------------------------------------------------
-- B. 이상치 탐지 — IQR 기반 (Q1 - 1.5*IQR, Q3 + 1.5*IQR)
-- --------------------------------------------------------

-- B-1. 유동인구 이상치
SELECT
    'VISITING_POPULATION' AS metric,
    PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY VISITING_POPULATION) AS q1,
    PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY VISITING_POPULATION) AS median,
    PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY VISITING_POPULATION) AS q3,
    PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY VISITING_POPULATION) -
        PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY VISITING_POPULATION) AS iqr,
    MIN(VISITING_POPULATION) AS min_val,
    MAX(VISITING_POPULATION) AS max_val,
    AVG(VISITING_POPULATION) AS mean_val,
    COUNT(CASE WHEN VISITING_POPULATION < 0 THEN 1 END) AS negative_count
FROM SEOUL_DISTRICTLEVEL_DATA_FLOATING_POPULATION_CONSUMPTION_AND_ASSETS
    .GRANDATA.FLOATING_POPULATION_INFO;

-- B-2. 매매가 이상치 (서울)
SELECT
    'MEME_PRICE' AS metric,
    PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY MEME_PRICE_PER_SUPPLY_PYEONG) AS q1,
    PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY MEME_PRICE_PER_SUPPLY_PYEONG) AS median,
    PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY MEME_PRICE_PER_SUPPLY_PYEONG) AS q3,
    MIN(MEME_PRICE_PER_SUPPLY_PYEONG) AS min_val,
    MAX(MEME_PRICE_PER_SUPPLY_PYEONG) AS max_val,
    AVG(MEME_PRICE_PER_SUPPLY_PYEONG) AS mean_val,
    COUNT(CASE WHEN MEME_PRICE_PER_SUPPLY_PYEONG <= 0 THEN 1 END) AS zero_or_neg
FROM KOREAN_POPULATION__APARTMENT_MARKET_PRICE_DATA
    .HACKATHON_2025Q2.REGION_APT_RICHGO_MARKET_PRICE_M_H
WHERE SD = '서울';

-- B-3. 소득 이상치
SELECT
    'AVERAGE_INCOME' AS metric,
    PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY AVERAGE_INCOME) AS q1,
    PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY AVERAGE_INCOME) AS median,
    PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY AVERAGE_INCOME) AS q3,
    MIN(AVERAGE_INCOME) AS min_val,
    MAX(AVERAGE_INCOME) AS max_val,
    AVG(AVERAGE_INCOME) AS mean_val
FROM SEOUL_DISTRICTLEVEL_DATA_FLOATING_POPULATION_CONSUMPTION_AND_ASSETS
    .GRANDATA.ASSET_INCOME_INFO;


-- --------------------------------------------------------
-- C. 0값 비율 체크 — 매출 0은 NULL과 같은 의미일 수 있음
-- --------------------------------------------------------

SELECT
    COUNT(*) AS total_rows,
    ROUND(SUM(CASE WHEN TOTAL_SALES = 0 THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) AS zero_pct_total_sales,
    ROUND(SUM(CASE WHEN COFFEE_SALES = 0 THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) AS zero_pct_coffee,
    ROUND(SUM(CASE WHEN ENTERTAINMENT_SALES = 0 THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) AS zero_pct_entertainment,
    ROUND(SUM(CASE WHEN E_COMMERCE_SALES = 0 THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) AS zero_pct_ecom
FROM SEOUL_DISTRICTLEVEL_DATA_FLOATING_POPULATION_CONSUMPTION_AND_ASSETS
    .GRANDATA.CARD_SALES_INFO;
