-- ============================================================
-- 04. JOIN 키 검증 — DB 간 지역 코드 매핑 가능성 확인
-- DONGNE_MASTER 설계를 위한 사전 검증
-- 크레딧: ~$0.02
-- ============================================================

-- --------------------------------------------------------
-- A. SPH 지역 마스터 (M_SCCO_MST) 전체 구조 확인
-- 이것이 JOIN 허브가 될 테이블
-- --------------------------------------------------------

SELECT *
FROM SEOUL_DISTRICTLEVEL_DATA_FLOATING_POPULATION_CONSUMPTION_AND_ASSETS
    .GRANDATA.M_SCCO_MST
LIMIT 20;

-- 서울 구 목록
SELECT DISTINCT CITY_KOR_NAME, DISTRICT_KOR_NAME, CITY_CODE, DISTRICT_CODE
FROM SEOUL_DISTRICTLEVEL_DATA_FLOATING_POPULATION_CONSUMPTION_AND_ASSETS
    .GRANDATA.M_SCCO_MST
WHERE PROVINCE_KOR_NAME = '서울특별시'
  OR PROVINCE_KOR_NAME LIKE '서울%'
ORDER BY CITY_KOR_NAME, DISTRICT_KOR_NAME;


-- --------------------------------------------------------
-- B. 리치고 ↔ SPH 매핑 검증
-- 리치고: SD/SGG/EMD (텍스트), SPH: CITY_CODE/DISTRICT_CODE (코드)
-- 매핑: 리치고.SGG = SPH.CITY_KOR_NAME
-- --------------------------------------------------------

-- B-1. 리치고 서울 구 목록
SELECT DISTINCT SGG
FROM KOREAN_POPULATION__APARTMENT_MARKET_PRICE_DATA
    .HACKATHON_2025Q2.REGION_APT_RICHGO_MARKET_PRICE_M_H
WHERE SD = '서울'
ORDER BY SGG;

-- B-2. SPH 서울 구 목록
SELECT DISTINCT CITY_KOR_NAME
FROM SEOUL_DISTRICTLEVEL_DATA_FLOATING_POPULATION_CONSUMPTION_AND_ASSETS
    .GRANDATA.M_SCCO_MST
WHERE PROVINCE_KOR_NAME = '서울특별시'
  OR PROVINCE_KOR_NAME LIKE '서울%'
ORDER BY CITY_KOR_NAME;

-- B-3. 매칭 결과 — 리치고 SGG와 SPH CITY_KOR_NAME 교차 확인
SELECT
    r.SGG AS richgo_sgg,
    m.CITY_KOR_NAME AS sph_city,
    CASE WHEN m.CITY_KOR_NAME IS NOT NULL THEN 'MATCH' ELSE 'NO MATCH' END AS status
FROM (
    SELECT DISTINCT SGG
    FROM KOREAN_POPULATION__APARTMENT_MARKET_PRICE_DATA
        .HACKATHON_2025Q2.REGION_APT_RICHGO_MARKET_PRICE_M_H
    WHERE SD = '서울'
) r
LEFT JOIN (
    SELECT DISTINCT CITY_KOR_NAME
    FROM SEOUL_DISTRICTLEVEL_DATA_FLOATING_POPULATION_CONSUMPTION_AND_ASSETS
        .GRANDATA.M_SCCO_MST
) m ON r.SGG = m.CITY_KOR_NAME
ORDER BY r.SGG;


-- --------------------------------------------------------
-- C. SPH 내부 키 일관성 — 유동인구/카드소비/자산소득이 같은 키 사용하는지
-- --------------------------------------------------------

-- C-1. 유동인구 구 코드 목록
SELECT DISTINCT CITY_CODE, DISTRICT_CODE
FROM SEOUL_DISTRICTLEVEL_DATA_FLOATING_POPULATION_CONSUMPTION_AND_ASSETS
    .GRANDATA.FLOATING_POPULATION_INFO
ORDER BY CITY_CODE, DISTRICT_CODE;

-- C-2. 카드소비 구 코드 목록
SELECT DISTINCT CITY_CODE, DISTRICT_CODE
FROM SEOUL_DISTRICTLEVEL_DATA_FLOATING_POPULATION_CONSUMPTION_AND_ASSETS
    .GRANDATA.CARD_SALES_INFO
ORDER BY CITY_CODE, DISTRICT_CODE;

-- C-3. 자산/소득 구 코드 목록
SELECT DISTINCT CITY_CODE, DISTRICT_CODE
FROM SEOUL_DISTRICTLEVEL_DATA_FLOATING_POPULATION_CONSUMPTION_AND_ASSETS
    .GRANDATA.ASSET_INCOME_INFO
ORDER BY CITY_CODE, DISTRICT_CODE;

-- C-4. 3개 테이블 키 교차 검증 — 모두 매칭되는 구 수
SELECT
    COUNT(DISTINCT fp.CITY_CODE || '-' || fp.DISTRICT_CODE) AS fp_districts,
    COUNT(DISTINCT cs.CITY_CODE || '-' || cs.DISTRICT_CODE) AS cs_districts,
    COUNT(DISTINCT ai.CITY_CODE || '-' || ai.DISTRICT_CODE) AS ai_districts
FROM (SELECT DISTINCT CITY_CODE, DISTRICT_CODE
      FROM SEOUL_DISTRICTLEVEL_DATA_FLOATING_POPULATION_CONSUMPTION_AND_ASSETS
          .GRANDATA.FLOATING_POPULATION_INFO) fp
FULL OUTER JOIN (SELECT DISTINCT CITY_CODE, DISTRICT_CODE
      FROM SEOUL_DISTRICTLEVEL_DATA_FLOATING_POPULATION_CONSUMPTION_AND_ASSETS
          .GRANDATA.CARD_SALES_INFO) cs
    ON fp.CITY_CODE = cs.CITY_CODE AND fp.DISTRICT_CODE = cs.DISTRICT_CODE
FULL OUTER JOIN (SELECT DISTINCT CITY_CODE, DISTRICT_CODE
      FROM SEOUL_DISTRICTLEVEL_DATA_FLOATING_POPULATION_CONSUMPTION_AND_ASSETS
          .GRANDATA.ASSET_INCOME_INFO) ai
    ON COALESCE(fp.CITY_CODE, cs.CITY_CODE) = ai.CITY_CODE
    AND COALESCE(fp.DISTRICT_CODE, cs.DISTRICT_CODE) = ai.DISTRICT_CODE;


-- --------------------------------------------------------
-- D. 코드 마스터 확인 — SPH 코드 해석
-- --------------------------------------------------------

SELECT *
FROM SEOUL_DISTRICTLEVEL_DATA_FLOATING_POPULATION_CONSUMPTION_AND_ASSETS
    .GRANDATA.CODE_MASTER
LIMIT 30;


-- --------------------------------------------------------
-- E. REGION_LEVEL 확인 — 리치고 데이터 단위
-- --------------------------------------------------------

SELECT DISTINCT REGION_LEVEL, COUNT(*) AS cnt
FROM KOREAN_POPULATION__APARTMENT_MARKET_PRICE_DATA
    .HACKATHON_2025Q2.REGION_APT_RICHGO_MARKET_PRICE_M_H
WHERE SD = '서울'
GROUP BY REGION_LEVEL;
